[package]
name = "piet-wgpu"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ab_glyph = "0.2.11"
font-kit = "0.10.1"
lyon = "0.17.5"
piet = { git = "https://github.com/linebender/piet" }
wgpu = { version = "0.10.0", features = ["spirv"] }
futures = "0.3.17"
glam = "0.10"
raw-window-handle = "0.3.3"
bytemuck = { version = "1.7.2", features = ["derive"]}
