[package]
name = "piet-wgpu"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.8"
usvg = "0.14.0"
font-kit = "0.10.1"
linked-hash-map = "0.5.4"
rustc-hash = "1.1.0"
pathfinder_geometry = "0.5.1"
lyon = "0.17.5"
piet = "0.4.0"
wgpu = { version = "0.10.0", features = ["spirv"] }
futures = "0.3.17"
glam = "0.10"
raw-window-handle = "0.3.3"
bytemuck = { version = "1.7.2", features = ["derive"] }
